# The name of the product key for this product from mixlib-install
product_key:
  - chef
  - angrychef

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-notify

rubygems:
  - chef
  - chef-config

github:
  version_tag_format: "v{{version}}"
  maintainer_group: chef/client-core
  release_branch:
    master:
      version_constraint: ~> 13.0
    chef-12:
      version_constraint: ~> 12.0

merge_actions:
  built_in:bump_version:
    ignore_labels: "Version: Skip Bump"
  bash:.expeditor/update_version.sh:
    only_if: built_in:bump_version
  built_in:update_changelog:
    ignore_labels: "Meta: Exclude From Changelog"
  built_in:trigger_omnibus_release_build:
    ignore_labels: "Omnibus: Skip Build"
    only_if: built_in:bump_version

artifact_actions:
  promoted_to_unstable:
    built_in:build_docker_image:
  promoted_to_current:
    built_in:tag_docker_image:
  promoted_to_stable:
    built_in:tag_docker_image:
    built_in:publish_rubygems:
    built_in:rollover_changelog:
    bash:.expeditor/update_dockerfile.sh:
